<?php

namespace Upload\GFileBundle\Repository\GFile;

use Doctrine\ORM\EntityRepository;

/**
 * UploadFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadFileRepository extends EntityRepository
{
}
